### ISSUE TITLE
Console Errors After Cloning With Github Desktop

### ISSUE THREAD

**Issue by NerveCoordinator** [alloverse/allovisor-unity#13]
After cloning the repo using git desktop (for  LFS support as it says), I got errors after importing into unity. I got stuck on step 4: `Check the Console. It should have no errors. If it does, ask @nevyn or ping on Slack.` Unfortunately there were errors in the console. 

I couldn't find a link to the slack anywhere. Is it perhaps invite only? 

The two errors in the console (ignoring mere warnings for now):
```
Assets/Code/Editor/AlloVisorBuild.cs(4,19): error CS0234: The type or namespace name `iOS' does not exist in the namespace `UnityEditor'. Are you missing an assembly reference?
Assets/Code/Editor/AlloVisorBuild.cs(132,43): error CS0246: The type or namespace name `PlistDocument' could not be found. Are you missing an assembly reference?
```

I did use Unity 2018.3.13f1 instead of 2018.3.8f1. This was because I couldn't figure out how to download the specified one. Unsure if that's part of the issue or not. 

I think this is because of this note from the [getting started guide ](https://github.com/alloverse/docs/blob/master/GETTING_STARTED.md)

`Allovisor should build in Unity out of the box. The bundled liballonet.bundle is Mac-only, so if you want to develop on another platform, you have to compile and copy in the appropriate allonet binary into the Assets folder.`

I'm not entirely sure how to compile it. I've gotten the [alloplace server ](https://github.com/alloverse/alloplace) running, and it has allonet built inside of it. the build files appear to be in `_cmake/`. I am unsure what I would actually copy over from there, or to where.  Does it just mean replacing the `Assets/allonet.meta`, as well as `allonet.lock` and `allonet.lock.meta` files in `allovisor/Assets/allonet/`? If so, with what?

Searching for 'liballonet.bundle' in the repo shows it only in two places: mentioned in the .gitignore and in `Assets/Code/Editor/AlloVisorBuild.cs`. 

My current working assumption is that the instructions mean to copy the `_cmake/src/allonet/liballonet.so` file over, so I'll investigate that next. Unsure if '.so' is actually considered a binary, but it is the closest thing I have found so far.

**Comment by nevyn** [comment]
@NerveCoordinator Ah, so sorry for the issues! It seems the Getting Started is out of date. The things that seem to be going wrong for you:

* You need to install the iOS build support when you install Unity. It contains tools needed to build the Mac app. I'll add this to the readme.
* liballonet.bundle no longer needs to be compiled manually. As per the README in this project, you can just download it automatically from a menu option in the editor. I'll update the getting started to match, sorry for leading you down a rabbit hole.
* Unity Hub can be used to install arbitrary Unity versions. We try to stay up to date, but it's difficult and even for this small project introduces small incompatibilites with each update.
* Instead of running your own alloplace server, you can connect to alloplace://nevyn.places.alloverse.com . It should always be online :) If my docker-fu holds...

The slack is indeed invite only for now. Can I invite you? What's a good email I can send it to, if so?

**Comment by nevyn** [comment]
@NerveCoordinator I've now updated the Getting Started guide to be up to date :) Mostly by pointing it READMEs instead of talking about how other repos work.

I've also made the Slack invite link public, you can try it out here: https://join.slack.com/t/alloverse/shared_invite/enQtNTE3NTI3Mjc5NzUxLTBhNjExOTExOWZiZjAyYmFkOTNkMDBkMGE2MTlhMjU1NmJmZDVjOGRhNGVkMTRlZTJhODlkOTYyMmYzYTJkMzU

**Comment by NerveCoordinator** [comment]
Tried it again, this time got errors about OpenVR. Unfortunately my setup currently only works with OpenHMD and OpenXR. (No base stations for my Vive HMD, alas OpenVR doesn't like that.) Should have checked this before trying to use it. But that's out of scope.

Closing this as the specific issues were addressed.

**Comment by nevyn** [comment]
Ah, bummer! We're currently hard-coding Oculus stuff because that's the hardware all of the current devs have. Would love to be more cross platform though :)
